Set-ADUser -Identity "alice.chen" -Title "Registered Nurse"
Set-ADUser -Identity "ben.okafor" -Title "Registered Nurse"
Set-ADUser -Identity "david.kim" -Title "Medical Records Clerk"
Set-ADUser -Identity "elena.petrova" -Title "ICU Nurse"
Set-ADUser -Identity "henry.wu" -Title "Clinical Technician"
Set-ADUser -Identity "frank.miller" -Title "ICU Nurse"
Set-ADUser -Identity "carla.diaz" -Title "Radiology Technician"
Set-ADUser -Identity "michael.torres" -Title "Radiology Technician"
Set-ADUser -Identity "imaging-shared" -Title "Shared Imaging Workstation Login"
